{
 "title": "delay_analysis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SADDR",
    "label": "SADDR",
    "query": "SHOW TAG VALUES WITH KEY = \"SADDR\""
   },
   {
    "name": "SPORT",
    "label": "SPORT",
    "query": "SHOW TAG VALUES WITH KEY = \"SPORT\" WHERE \"SADDR\" =~ /^$SADDR$/"
   },
   {
    "name": "DADDR",
    "label": "DADDR",
    "query": "SHOW TAG VALUES WITH KEY = \"DADDR\" WHERE \"SADDR\" =~ /^$SADDR$/ and \"SPORT\" =~ /^$SPORT$/"
   },
   {
    "name": "DPORT",
    "label": "DPORT",
    "query": "SHOW TAG VALUES WITH KEY = \"DPORT\" WHERE \"SADDR\" =~ /^$SADDR$/ and \"SPORT\" =~ /^$SPORT$/ and \"DADDR\" =~ /^$DADDR$/"
   }
  ]
 },
 "panels": [
  {
   "title": "delay_analysis_out",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Qdisc",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_out",
     "query": "SELECT mean(\"TIME_QDisc\") FROM \"delay_analysis_out\" WHERE (\"SADDR\" =~ /^$SADDR$/ AND \"SPORT\" =~ /^$SPORT$/ AND \"DADDR\" =~ /^$DADDR$/ AND \"DPORT\" =~ /^$DPORT$/) AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "TIME_QDisc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SADDR", "operator": "=~", "value": "/^$SADDR$/" },
      { "condition": "AND", "key": "SPORT", "operator": "=~", "value": "/^$SPORT$/" },
      { "condition": "AND", "key": "DADDR", "operator": "=~", "value": "/^$DADDR$/" },
      { "condition": "AND", "key": "DPORT", "operator": "=~", "value": "/^$DPORT$/" }
     ]
    },
    {
     "alias": "ip",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_out",
     "query": "SELECT mean(\"TIME_IP\") FROM \"delay_analysis_in\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "TIME_IP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SADDR", "operator": "=~", "value": "/^$SADDR$/" },
      { "condition": "AND", "key": "SPORT", "operator": "=~", "value": "/^$SPORT$/" },
      { "condition": "AND", "key": "DADDR", "operator": "=~", "value": "/^$DADDR$/" },
      { "condition": "AND", "key": "DPORT", "operator": "=~", "value": "/^$DPORT$/" }
     ]
    },
    {
     "alias": "tcp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_out",
     "select": [
      [
       { "params": [ "TIME_TCP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SADDR", "operator": "=~", "value": "/^$SADDR$/" },
      { "condition": "AND", "key": "SPORT", "operator": "=~", "value": "/^$SPORT$/" },
      { "condition": "AND", "key": "DADDR", "operator": "=~", "value": "/^$DADDR$/" },
      { "condition": "AND", "key": "DPORT", "operator": "=~", "value": "/^$DPORT$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_out",
     "select": [
      [
       { "params": [ "TIME_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SADDR", "operator": "=~", "value": "/^$SADDR$/" },
      { "condition": "AND", "key": "SPORT", "operator": "=~", "value": "/^$SPORT$/" },
      { "condition": "AND", "key": "DADDR", "operator": "=~", "value": "/^$DADDR$/" },
      { "condition": "AND", "key": "DPORT", "operator": "=~", "value": "/^$DPORT$/" }
     ]
    }
   ]
  },
  {
   "title": "nic_throughput_TX_PPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nic_throughput_TX",
     "select": [
      [
       { "params": [ "PPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "delay_analysis_in",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "mac",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_in",
     "query": "SELECT mean(\"TIME_MAC\") FROM \"delay_analysis_in\" WHERE (\"SADDR\" =~ /^$SADDR$/ AND \"SPORT\" =~ /^$SPORT$/ AND \"DADDR\" =~ /^$DADDR$/ AND \"DPORT\" =~ /^$SPORT$/) AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "TIME_MAC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SADDR", "operator": "=~", "value": "/^$SADDR$/" },
      { "condition": "AND", "key": "SPORT", "operator": "=~", "value": "/^$SPORT$/" },
      { "condition": "AND", "key": "DADDR", "operator": "=~", "value": "/^$DADDR$/" },
      { "condition": "AND", "key": "DPORT", "operator": "=~", "value": "/^$DPORT$/" }
     ]
    },
    {
     "alias": "ip",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_in",
     "query": "SELECT mean(\"TIME_IP\") FROM \"delay_analysis_in\" WHERE (\"SADDR\" =~ /^$SADDR$/ AND \"SPORT\" =~ /^$SPORT$/ AND \"DADDR\" =~ /^$DADDR$/ AND \"DPORT\" =~ /^$DPORT$/) $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "TIME_IP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "tcp",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_in",
     "query": "SELECT mean(\"TIME_TCP\") FROM \"delay_analysis_in\" WHERE (\"SADDR\" =~ /^$SADDR$/ AND \"SPORT\" =~ /^$SPORT$/ AND \"DADDR\" =~ /^$DADDR$/ AND \"DPORT\" =~ /^$DPORT$/) $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "TIME_TCP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "delay_analysis_in",
     "query": "SELECT mean(\"TIME_TOTAL\") FROM \"delay_analysis_in\" WHERE (\"SADDR\" =~ /^$SADDR$/ AND \"SPORT\" =~ /^$SPORT$/ AND \"DADDR\" =~ /^$DADDR$/ AND \"DPORT\" =~ /^$DPORT$/) $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "TIME_TOTAL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}