# TODO: Add options to configure ports and credentials of InfluxDB and Grafana

services:
  influxdb:
    image: influxdb:1.8
    restart: always
    environment:
      - INFLUXDB_DB=network_subsystem
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro

  grafana:
    image: grafana:seu
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro

volumes:
  influxdb-data: {}
  grafana-data: {}
