name: Build artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up cache for container image layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build artifacts
        run: |
          sudo apt-get update && \
          sudo apt-get install -y zlib1g-dev libelf-dev llvm && \
          make -j$(nproc)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: network_tracing-artifacts
          path: dist/
